version: 1.0.{build}
configuration: Release

# scripts to run before build
before_build:
- cmd: >-
    nuget restore Proverb.sln

#build:
#  project: Proverb.sln
#  publish_wap: true
#  verbosity: minimal

build_script:
- cmd: >-
    msbuild Proverb.sln /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    cd Proverb.Web

    msbuild Proverb.Web.csproj /t:Package /p:PackageLocation=..\Proverb.Web.zip

    cd ..

artifacts:
- path: Proverb.Web.zip
  name: WebApplication
  type: WebDeployPackage

deploy:
- provider: WebDeploy
  server:
    secure: NvzatElBACvT9rl9q93l4Ou1LdB7WvF4cAV61SyergZ20myLeUxsCfsUkgsGTcjC8Khw2jC0HrTdJsGrfwx2YCI90yYgC7xqDnGF4TLpnc0=
  website: proverbsignalr
  username:
    secure: oD4cIsHoIqRcFMmFj6OKMw==
  password:
    secure: Q3+FzAapY0SepeyiyDjJLHw5rbSAMOoYkvUlYVPJR0GM3WTBb6BZ0MAP3VurafJme4gCyExesUB/hmMFKNAsnA==
  remove_files: true
