version: 1.0.{build}
os: Visual Studio 2015 CTP
configuration: Release

# scripts to run before build
before_build:
- cmd: >-
    nuget restore Proverb.sln

    npm install -g bower
    
    npm install -g gulp

    cd Proverb.Web

    bower install
    
    npm install

    gulp release-build

    cd ..

#build:
#  project: Proverb.sln
#  publish_wap: true
#  verbosity: minimal

build_script:
- cmd: >-
    # Full build of solution takes place

    msbuild Proverb.sln /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"


    # JavaScript files created from TypeScript are turned into build artefacts by Gulp

    gulp release-build


    # Everything that has been built gets packaged

    msbuild Proverb.Web\Proverb.Web.csproj /t:Package /p:PackageLocation=Proverb.Web.zip

before_test:
- ps: >-
    # Locate Chutzpah

    $ChutzpahDir = get-childitem chutzpah.console.exe -recurse | select-object -first 1 | select -expand Directory
    
    # Run tests using Chutzpah and export results as JUnit format to chutzpah-results.xml

    $ChutzpahCmd = "$($ChutzpahDir)\chutzpah.console.exe $($env:APPVEYOR_BUILD_FOLDER)\Proverb.Web.Tests.JavaScript /junit .\chutzpah-results.xml"

    Write-Host $ChutzpahCmd

    Invoke-Expression $ChutzpahCmd

    # Upload results to AppVeyor one by one

    $testsuites = [xml](get-content .\chutzpah-results.xml)
    
    $anyFailures = $FALSE

    foreach ($testsuite in $testsuites.testsuites.testsuite) {

        write-host " $($testsuite.name)"

        foreach ($testcase in $testsuite.testcase){

            $failed = $testcase.failure

            $time = $testsuite.time

            if ($testcase.time) { $time = $testcase.time }

            if ($failed) {

                write-host "Failed   $($testcase.name) $($testcase.failure.message)"

                Add-AppveyorTest $testcase.name -Outcome Failed -FileName $testsuite.name -ErrorMessage $testcase.failure.message -Duration $time

            }

            else {

                write-host "Passed   $($testcase.name)"

                Add-AppveyorTest $testcase.name -Outcome Passed -FileName $testsuite.name -Duration $time

            }

        }

    }
    
    if ($anyFailures -eq $TRUE){

        write-host "Failing build as there are broken tests"

        $host.SetShouldExit(1)

    }

deploy:
- provider: WebDeploy
  server:
    secure: NvzatElBACvT9rl9q93l4Ou1LdB7WvF4cAV61SyergZ20myLeUxsCfsUkgsGTcjC8Khw2jC0HrTdJsGrfwx2YCI90yYgC7xqDnGF4TLpnc0=
  website: proverb
  username:
    secure: hF4z+9jP+et7duuTVWcVBw==
  password:
    secure: dSc6RSokZrmvp0+a4tYUSJhsVUN+IasvnJ8LrQpQCoqUOIfYF5TbNK7E6MGGH1K7ao3UzrSUodQ18KJhhvsI9g==
  remove_files: true
